import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from './components/layout/Footer/Footer';
import Header from './components/layout/Header/Header';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Shelter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
